title: Workspace
email: aaryaki@dev
description: >-
  Blogs, miscellaneous articles
baseurl: "/"
url: "https://aaryaki.github.io/"
author: Aaryaki


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

paginate: 4
show_excerpts: true
